name: OpeningPMnS
main: princepines\OpeningPMnS\main
version: 1.0.0
api: 3.0.0
author: Lycol50
description: Opening event for PMnS
commands:
  launch:
    description: Launch Fireworks and Music
    default: op
  intro:
    description: Start Introduction
    default: op